apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-registry-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-registry-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50